version: '3.8'

services:
  app:
    image: matesome 
    build:
      context: . 
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: postgres://user:password@db:5432 
      MONGO_URL: mongodb://mongo:27017  
    depends_on:
      - db
      - mongo

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: password  
      POSTGRES_DB: users
    volumes:
      - pg_data:/var/lib/postgresql/data 

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db  
  
